import { assessmentFieldLabels } from "../../data/assessment";
import { appointmentLifecyclePolicy } from "../../data/booking";
import { contactInterestOptions } from "../../data/contact";
import { siteConfig } from "../../data/site";
import type { AssessmentFormData, AssessmentField } from "../../types/assessment";
import type { ServiceAgreementData } from "../../types/agreement";
import type { AppointmentRecord, ConsultationType } from "../../types/booking";
import type { ContactLead } from "../../types/lead";

type Template = {
  subject: string;
  text: string;
  html: string;
};

type AddressedTemplate = Template & {
  to: string;
};

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatLine(label: string, value: string) {
  return `${label}: ${value || "Not provided"}`;
}

function paragraph(value: string) {
  return `<p style="margin:0 0 16px;color:#3f4f4a;line-height:1.6;">${escapeHtml(value)}</p>`;
}

function htmlShell(title: string, body: string) {
  return `<!doctype html>
<html>
  <body style="margin:0;background:#f6f8f5;font-family:Arial,sans-serif;color:#10231e;">
    <div style="max-width:680px;margin:0 auto;padding:28px;">
      <div style="background:#ffffff;border:1px solid #dbe3df;border-radius:8px;padding:28px;">
        <p style="margin:0 0 8px;color:#b63f37;font-size:12px;font-weight:700;text-transform:uppercase;">${escapeHtml(siteConfig.businessName)}</p>
        <h1 style="margin:0 0 20px;font-size:26px;line-height:1.2;color:#10231e;">${escapeHtml(title)}</h1>
        ${body}
      </div>
    </div>
  </body>
</html>`;
}

function detailsList(items: Array<{ label: string; value: string }>) {
  return `<dl style="margin:0;display:grid;gap:12px;">
    ${items
      .map(
        (item) => `<div style="border-top:1px solid #dbe3df;padding-top:12px;">
          <dt style="font-size:12px;font-weight:700;color:#10231e;text-transform:uppercase;">${escapeHtml(item.label)}</dt>
          <dd style="margin:4px 0 0;color:#3f4f4a;line-height:1.6;white-space:pre-line;">${escapeHtml(item.value || "Not provided")}</dd>
        </div>`,
      )
      .join("")}
  </dl>`;
}

function contactInterestLabel(value: string) {
  return (
    contactInterestOptions.find((option) => option.value === value)?.label ?? value
  );
}

export function createContactNotificationEmail(lead: ContactLead): Template {
  const items = [
    { label: "Name", value: lead.fullName },
    { label: "Email", value: lead.email },
    { label: "Phone", value: lead.phone },
    { label: "Country of residence", value: lead.country },
    { label: "Immigration interest", value: contactInterestLabel(lead.interest) },
    { label: "Message", value: lead.message },
  ];
  const text = [
    "New contact form submission",
    "",
    ...items.map((item) => formatLine(item.label, item.value)),
    "",
    "This message was generated by the website lead workflow.",
  ].join("\n");

  return {
    subject: `New contact enquiry: ${lead.fullName}`,
    text,
    html: htmlShell("New contact enquiry", detailsList(items)),
  };
}

export function createAssessmentNotificationEmail(
  assessment: AssessmentFormData,
): Template {
  const fields = Object.keys(assessmentFieldLabels) as AssessmentField[];
  const items = fields.map((field) => ({
    label: assessmentFieldLabels[field],
    value:
      field === "consent" && assessment[field] === "yes"
        ? "Consent provided"
        : assessment[field],
  }));
  const text = [
    "New immigration assessment submission",
    "",
    ...items.map((item) => formatLine(item.label, item.value)),
    "",
    "This message was generated by the website lead workflow.",
  ].join("\n");

  return {
    subject: `New immigration assessment: ${assessment.fullName}`,
    text,
    html: htmlShell("New immigration assessment", detailsList(items)),
  };
}

export function createClientConfirmationEmail(
  recipientName: string,
  kind: "contact" | "assessment",
): Template {
  const title =
    kind === "assessment"
      ? "Your immigration assessment was received"
      : "Your enquiry was received";
  const intro =
    kind === "assessment"
      ? "Thank you for submitting your immigration assessment. The information will be reviewed to help identify possible options and sensible next steps."
      : "Thank you for contacting Switch North Immigration. Your enquiry will be reviewed so the next step can be determined.";
  const text = [
    `Hello ${recipientName},`,
    "",
    intro,
    "",
    "This confirmation does not create a consultant-client relationship and does not guarantee any immigration outcome.",
    "",
    siteConfig.businessName,
  ].join("\n");
  const body = [
    paragraph(`Hello ${recipientName},`),
    paragraph(intro),
    paragraph(
      "This confirmation does not create a consultant-client relationship and does not guarantee any immigration outcome.",
    ),
  ].join("");

  return {
    subject: title,
    text,
    html: htmlShell(title, body),
  };
}

export function createAppointmentConfirmationEmail({
  appointment,
  consultationType,
}: {
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
}): Template {
  const items = [
    { label: "Client", value: appointment.client.fullName },
    { label: "Consultation", value: consultationType.title },
    { label: "Date", value: appointment.date },
    {
      label: "Time",
      value: `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`,
    },
    { label: "Payment", value: "Confirmed" },
  ];
  const text = [
    `Hello ${appointment.client.fullName},`,
    "",
    "Your consultation payment was received and your appointment is confirmed.",
    "",
    ...items.map((item) => formatLine(item.label, item.value)),
    "",
    "Please keep any relevant immigration documents and questions ready for the consultation.",
    "",
    "This confirmation does not guarantee any immigration outcome.",
    "",
    siteConfig.businessName,
  ].join("\n");
  const body = [
    paragraph(`Hello ${appointment.client.fullName},`),
    paragraph("Your consultation payment was received and your appointment is confirmed."),
    detailsList(items),
    paragraph(
      "Please keep any relevant immigration documents and questions ready for the consultation.",
    ),
    paragraph("This confirmation does not guarantee any immigration outcome."),
  ].join("");

  return {
    subject: "Your consultation is confirmed",
    text,
    html: htmlShell("Consultation confirmed", body),
  };
}

export function createServiceAgreementEmail({
  agreement,
  appointment,
  consultationType,
  managementUrl,
}: {
  agreement: ServiceAgreementData;
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
  managementUrl?: string;
}): Template {
  const appointmentTime = `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`;
  const text = [
    `Hello ${agreement.clientName},`,
    "",
    `Thank you for booking your consultation with ${agreement.businessName}.`,
    "",
    "Your appointment has been confirmed for:",
    "",
    `Date: ${appointment.date}`,
    `Time: ${appointmentTime}`,
    `Consultation: ${consultationType.title}`,
    "",
    ...(managementUrl
      ? [
          "Manage your appointment securely:",
          managementUrl,
          "",
        ]
      : []),
    "Please find your Service Agreement attached.",
    "",
    "Please review the agreement carefully before your appointment.",
    "",
    "If you have any questions regarding the agreement, please contact us before your scheduled consultation.",
    "",
    "Regards,",
    "",
    agreement.consultantName,
    agreement.businessName,
    agreement.businessEmail,
    agreement.businessPhone,
  ].join("\n");
  const body = [
    paragraph(`Hello ${agreement.clientName},`),
    paragraph(`Thank you for booking your consultation with ${agreement.businessName}.`),
    detailsList([
      { label: "Date", value: appointment.date },
      { label: "Time", value: appointmentTime },
      { label: "Consultation", value: consultationType.title },
      ...(managementUrl ? [{ label: "Manage appointment", value: managementUrl }] : []),
    ]),
    paragraph("Please find your Service Agreement attached."),
    paragraph("Please review the agreement carefully before your appointment."),
    paragraph(
      "If you have any questions regarding the agreement, please contact us before your scheduled consultation.",
    ),
    paragraph(
      `Regards,\n${agreement.consultantName}\n${agreement.businessName}\n${agreement.businessEmail}\n${agreement.businessPhone}`,
    ),
  ].join("");

  return {
    subject: `Service Agreement - ${agreement.businessName}`,
    text,
    html: htmlShell("Service Agreement", body),
  };
}

export function createRescheduledAppointmentEmail({
  appointment,
  consultationType,
  managementUrl,
}: {
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
  managementUrl: string;
}): AddressedTemplate {
  const appointmentTime = `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`;
  const title = "Your consultation has been rescheduled";
  const items = [
    { label: "Client", value: appointment.client.fullName },
    { label: "Consultation", value: consultationType.title },
    { label: "New date", value: appointment.date },
    { label: "New time", value: appointmentTime },
    { label: "Duration", value: `${consultationType.durationMinutes} minutes` },
    { label: "Manage appointment", value: managementUrl },
  ];

  return {
    html: htmlShell(
      title,
      [
        paragraph(`Hello ${appointment.client.fullName},`),
        paragraph("Your consultation appointment has been rescheduled."),
        detailsList(items),
        paragraph(`Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`),
      ].join(""),
    ),
    subject: title,
    text: [
      `Hello ${appointment.client.fullName},`,
      "",
      "Your consultation appointment has been rescheduled.",
      "",
      ...items.map((item) => formatLine(item.label, item.value)),
      "",
      `Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`,
    ].join("\n"),
    to: appointment.client.email,
  };
}

export function createCancelledAppointmentEmail({
  appointment,
  consultationType,
}: {
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
}): AddressedTemplate {
  const appointmentTime = `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`;
  const title = "Your consultation has been cancelled";
  const items = [
    { label: "Client", value: appointment.client.fullName },
    { label: "Consultation", value: consultationType.title },
    { label: "Cancelled appointment", value: `${appointment.date}, ${appointmentTime}` },
    { label: "Refund status", value: appointment.refundStatus ?? "NOT_REQUESTED" },
  ];

  return {
    html: htmlShell(
      title,
      [
        paragraph(`Hello ${appointment.client.fullName},`),
        paragraph("Your consultation appointment has been cancelled."),
        detailsList(items),
        paragraph(appointmentLifecyclePolicy.refundPolicyNotice),
        paragraph(`Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`),
      ].join(""),
    ),
    subject: title,
    text: [
      `Hello ${appointment.client.fullName},`,
      "",
      "Your consultation appointment has been cancelled.",
      "",
      ...items.map((item) => formatLine(item.label, item.value)),
      "",
      appointmentLifecyclePolicy.refundPolicyNotice,
      "",
      `Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`,
    ].join("\n"),
    to: appointment.client.email,
  };
}

export function createAppointmentReminderEmail({
  appointment,
  consultationType,
  managementUrl,
  reminderType,
}: {
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
  managementUrl: string;
  reminderType: "REMINDER_24_HOUR" | "REMINDER_2_HOUR";
}): AddressedTemplate {
  const appointmentTime = `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`;
  const title =
    reminderType === "REMINDER_24_HOUR"
      ? "Consultation reminder: 24 hours"
      : "Consultation reminder: 2 hours";
  const items = [
    { label: "Consultation", value: consultationType.title },
    { label: "Date", value: appointment.date },
    { label: "Time", value: appointmentTime },
    { label: "Duration", value: `${consultationType.durationMinutes} minutes` },
    { label: "Meeting/location", value: "To be confirmed by Switch North Immigration" },
    { label: "Manage appointment", value: managementUrl },
  ];

  return {
    html: htmlShell(
      title,
      [
        paragraph(`Hello ${appointment.client.fullName},`),
        paragraph("This is a reminder for your upcoming consultation."),
        detailsList(items),
        paragraph(`Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`),
      ].join(""),
    ),
    subject: title,
    text: [
      `Hello ${appointment.client.fullName},`,
      "",
      "This is a reminder for your upcoming consultation.",
      "",
      ...items.map((item) => formatLine(item.label, item.value)),
      "",
      `Questions? Contact ${siteConfig.email} or ${siteConfig.phone}.`,
    ].join("\n"),
    to: appointment.client.email,
  };
}

export function createManagementLinkEmail({
  appointment,
  consultationType,
  managementUrl,
}: {
  appointment: AppointmentRecord;
  consultationType: ConsultationType;
  managementUrl: string;
}): AddressedTemplate {
  const title = "Manage your consultation appointment";

  return {
    html: htmlShell(
      title,
      [
        paragraph(`Hello ${appointment.client.fullName},`),
        paragraph("Use the secure link below to view or manage your consultation appointment."),
        detailsList([
          { label: "Consultation", value: consultationType.title },
          { label: "Date", value: appointment.date },
          {
            label: "Time",
            value: `${appointment.startTime} - ${appointment.endTime} ${appointment.timeZone}`,
          },
          { label: "Manage appointment", value: managementUrl },
        ]),
      ].join(""),
    ),
    subject: title,
    text: [
      `Hello ${appointment.client.fullName},`,
      "",
      "Use the secure link below to view or manage your consultation appointment.",
      "",
      managementUrl,
    ].join("\n"),
    to: appointment.client.email,
  };
}
